---
  extends: airbnb-base
  env:
    node: true
    mocha: true
    es6: true
    commonjs: true

  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures:
      modules: true
  rules:
    # begin msynk definitions
    linebreak-style: ["error", "windows"]
    space-before-function-paren: ["error", {
        "anonymous": "never",
        "named": "never",
        "asyncArrow": "never"
    }]
    indent: ["off", 4, { "ignoreComments": true }]
    no-trailing-spaces: ["off", { "ignoreComments": true }]
    no-extra-semi: 1
    semi: [2, "always"]
    no-undef: 0
    no-useless-constructor: 0
    no-empty-function: 0
    max-len:
      - 2
      - 160
      - 2
    arrow-body-style: ["warn", "as-needed"]
    no-unused-vars: ["off", { "vars": "local" }]
    class-methods-use-this: ["warn", { "exceptMethods": ["routeGet", "routePost", "routeDelete", "routePatch", "order", "_addRoute"] }]
    no-continue: "warn"
    no-restricted-syntax: ["off",
      'ForOfInStatement',
      'ForInStatement'
    ]
    no-useless-escape: "warn"
    prefer-destructuring: ["warn", {"object": true, "array": false}]
    import/no-duplicates: "warn" # https://stackoverflow.com/questions/45867553/es6-typescript-import-import-and-names-on-a-single-line
    no-console: "off"
    no-eval: "off"
    # end msynk definitions

    generator-star-spacing:
      - 2
      - before: true
        after: true
    no-shadow: 0
    import/no-unresolved: 0
    import/extensions: 0
    require-yield: 0
    no-param-reassign: 0
    comma-dangle: 0
    no-underscore-dangle: 0
    no-control-regex: 0
    import/no-extraneous-dependencies:
      - 2
      - devDependencies: true
    func-names: 0
    no-unused-expressions: 0
    prefer-arrow-callback: 1
    no-use-before-define:
      - 2
      - functions: false

    strict:
      - 2
      - global
    arrow-parens:
      - 2
      - always